version: '3.8'

services:
  db-postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  data-migration:
    image: homeacademy/data-migration
    environment:
      DATASOURCE_URL: jdbc:postgresql://db-postgres:5432/postgres?user=postgres&password=password
    ports:
      - 5000:5000
    depends_on:
      db-postgres:
        condition: service_healthy

  home-project:
    image: homeacademy/home-project
    environment:
      DATASOURCE_URL: jdbc:postgresql://db-postgres:5432/postgres
    ports:
      - 8080:8080
    depends_on:
      db-postgres:
        condition: service_healthy