version: '3.1'

services:
  data-base:
    image: postgres:latest
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432





