name: CI building project

on:  
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build data migration module
      run: mvn -pl .,home-data-migration clean install
    - name: Build with Maven
      run: mvn clean install -Pdocker

